# Generated by Django 6.0.1 on 2026-02-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_alter_question_options_question_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TF', 'True/False'), ('SHORT', 'Short Answer'), ('LONG', 'Long Answer'), ('NUMERICAL', 'Numerical/Mathematical')], default='SHORT', max_length=10),
        ),
    ]
