# Generated by Django 6.0.1 on 2026-02-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('theoretical', 'Theoretical'), ('numerical', 'Numerical'), ('mixed', 'Mixed')], default='mixed', max_length=20),
        ),
    ]
